# Generated by Django 5.1.7 on 2025-03-27 19:42

import django.db.models.deletion
from django.db import migrations, models


def create_categories(apps, schema_editor):
    # Get the Category model from the app registry
    Category = apps.get_model('blog', 'Category')

    # List of category names to insert
    categories = [
        'General',
        'Technology',
        'Random',
    ]

    # Insert each category name into the Category table
    for category_name in categories:
        Category.objects.get_or_create(name=category_name)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs',
                                                 to='blog.category')),
            ],
        ),
        # Add the migration to seed the Category table
        migrations.RunPython(create_categories),
    ]
